# Generated by Django 4.1.7 on 2023-02-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generate_question", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="text_to_questions",
            new_name="TextToQuestions",
        ),
    ]
